/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package snake;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author alu53788313f
 */
public class Game extends javax.swing.JFrame {

    private static boolean gameStarted;
    /**
     * Creates new form Game
     */
    public Game() {
        initComponents();
        board.setScore(scoreBoard);
        board.setParentFrame(this);
        gameStarted = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        board1 = new snake.Board();
        scoreBoard = new snake.ScoreBoard();
        board = new snake.Board();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuInitGame = new javax.swing.JMenuItem();
        jMenuReset = new javax.swing.JMenuItem();
        jMenuEdit = new javax.swing.JMenu();
        jMenuItemChangeDifficulty = new javax.swing.JMenuItem();

        javax.swing.GroupLayout board1Layout = new javax.swing.GroupLayout(board1);
        board1.setLayout(board1Layout);
        board1Layout.setHorizontalGroup(
            board1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );
        board1Layout.setVerticalGroup(
            board1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().add(scoreBoard, java.awt.BorderLayout.PAGE_END);

        board.setBackground(new java.awt.Color(51, 255, 255));

        javax.swing.GroupLayout boardLayout = new javax.swing.GroupLayout(board);
        board.setLayout(boardLayout);
        boardLayout.setHorizontalGroup(
            boardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );
        boardLayout.setVerticalGroup(
            boardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 293, Short.MAX_VALUE)
        );

        getContentPane().add(board, java.awt.BorderLayout.CENTER);

        jMenuFile.setText("File");

        jMenuInitGame.setText("Init Game");
        jMenuInitGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuInitGameActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuInitGame);

        jMenuReset.setText("Reset");
        jMenuFile.add(jMenuReset);

        jMenuBar1.add(jMenuFile);

        jMenuEdit.setText("Edit");

        jMenuItemChangeDifficulty.setText("Change Difficulty");
        jMenuItemChangeDifficulty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemChangeDifficultyActionPerformed(evt);
            }
        });
        jMenuEdit.add(jMenuItemChangeDifficulty);

        jMenuBar1.add(jMenuEdit);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuInitGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuInitGameActionPerformed
        // TODO add your handling code here:
        resetDifficulty();
        gameStarted = true;
        changeDifficulty();
        board.initGame();
    }//GEN-LAST:event_jMenuInitGameActionPerformed

    private void jMenuItemChangeDifficultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemChangeDifficultyActionPerformed
        // TODO add your handling code here:
        resetDifficulty();
        board.getTimer().stop();
        changeDifficulty();
        board.initGame();
    }//GEN-LAST:event_jMenuItemChangeDifficultyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });
    }

    private void changeDifficulty() {
        JFrame frame = new JFrame();
        if (gameStarted) {
           
            String[] options = new String[3];
            options[0] = new String("Hard");
            options[1] = new String("Medium");
            options[2] = new String("Easy");
            int gameMode = JOptionPane.showOptionDialog(frame.getContentPane(), "Select The Game Difficulty", "GameMode", 0, JOptionPane.INFORMATION_MESSAGE, null, options, null);
            switch (gameMode) {
                case 0:
                    board.hardMode = true;
                    break;
                case 1:
                    board.mediumMode = true;
                    break;
                case 2:
                    board.easyMode = true;
                    break;
                default:
                    board.mediumMode = true;
                    break;
            }
        }
        else {
            JOptionPane.showMessageDialog(frame, "Please initialize first the game ", "Error", JOptionPane.ERROR_MESSAGE);
            
        }
    }

    private void resetDifficulty() {
        board.hardMode = false;
        board.mediumMode = false;
        board.easyMode = false;
    }
    
    public static Boolean getGameStarted(){
        return gameStarted;
    }
    
    public static void setGameStarted(Boolean b){
        gameStarted = b;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private snake.Board board;
    private snake.Board board1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuEdit;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuInitGame;
    private javax.swing.JMenuItem jMenuItemChangeDifficulty;
    private javax.swing.JMenuItem jMenuReset;
    private snake.ScoreBoard scoreBoard;
    // End of variables declaration//GEN-END:variables
}
